### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bapple5** [scottbot95/RoR2ModManager#114]
**Describe the bug**
When I install mods, Steam does not recognize any of them.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 0.5.1]

**Additional context**

**Comment by scottbot95** [comment]
I'm not sure I understand the issue here as Steam doesn't have anything to do with the modding system.

Is Risk of Rain 2 not finding the mods? You should check that the RoR2 path is set correctly in the app preferences.

Also an easy test to see if it's at least configuring the mod loader properly is simply to see where a black terminal window appears when you launch RoR2. If that's not happening I would suggest checking that the RoR2 path is set correctly. You could also hit `ctrl+shift+i` in the mod manager to open the console and see if there are any errors (highlighted in red) that appear when you try to install mods.
