### ISSUE TITLE
[FEATURE] Disable a mod, but keep it in the list for update checks (move it away from the plugins folder)

### ISSUE THREAD

**Issue by JohnEdwa** [scottbot95/RoR2ModManager#128]
With the new content patch, a lot of the mods I use broke and will require an update to function. But currently, the mod manager only allows me to completely uninstall a mod which removes it from the list and I will then need to remember to manually check if there is an update.   
I would like the ability to disable a mod while keeping it in the list of "installed" mods, so I can keep track of when they are updated.

Currently, there is a workaround for this: simply manually move/remove the mod folder from the `BepInEx/Plugins` folder, and the mod manager will think the mod is still installed even though it isn't. If the mod is ever updated, the update will be installed re-enabling the mod.

**Comment by zeak56** [comment]
I've seen this with minecraft, but you could just have the mod edit the file names. For example FasterTPCharge.dll.disabled. It might require administrative access on the exe startup, but this could be an easier work around rather than having it move the folder. I also wouldn't know if that were true or not.
