### ISSUE TITLE
Enhancement: directly open config file of mod

### ISSUE THREAD

**Issue by laundmo** [scottbot95/RoR2ModManager#42]
basic idea: simple button that opens the config file in a built-in or default editor.

maybe even show the files as a simple form that limits what a user can enter (correct boolean, no characters where numbers should be etc.)

**Comment by scottbot95** [comment]
Definitely something I plan to do in the future. Also a button to open the mods folder in general in case you need to do some manual intervention.

**Comment by scottbot95** [comment]
Also after a quick look at the BepInEx config folder it looks like it might not be trivial to infer the config file name from the mod (since that data isn't included in the manifest).

The config files named using Reverse-DNS notation which is up to how the mod author decided to name it. Most seem to follow the pattern of `com.{author}.{mod_name}` but that can't be guaranteed. Probably if a button gets added it will just try to open a file at the path and give up if it can't find one.

**Comment by laundmo** [comment]
all i can tell you is that all the filenames in my config folder follow the pattern you mentioned, only that com. is sometimes dev. too
```
com.bepis.r2api.cfg 
com.funkfrog_sipondo.sharesuite.cfg 
com.kookehs.statsdisplay.cfg 
com.kuberoot.autoitempickup.cfg 
com.LukasMods.PermanentMountainChallangecfg 
com.PallesenProductions.TurretsShootRebar.cfg 
com.Tmmeh42.AccuratePings.cfg 
com.Tmmeh42.StealthySpawn.cfg 
dev.felixire.ChestPercantage. cfg 
dev.felixire.Command_Artifact.cfg 
dev.wildbook.multitudes.cfg 
dev.wildbook.toomanyfriends.cfg 
```

**Comment by laundmo** [comment]
if its on any help i threw together a RegEx that matches the config names and has group 1 as author and 2 as name
`(?:com|dev)\.(.*?)\.(.*?).cfg`
https://regex101.com/r/2t3Oo3/1/

**Comment by scottbot95** [comment]
A right click option has been added to install packages that will search for, and open if found, a config file.

There will be improvements to this system. See #51
